import { Metrics, DarkPalette } from "../theme.slint";
import { HorizontalBox, VerticalBox } from "layout.slint";

export component Panel inherits VerticalBox {
    in property <string> title: "Title";
    in property <TextHorizontalAlignment> title-alignment: left;

    j-rounding: Metrics.radius-md;

    Text {
        height: Metrics.size-md;
        color: DarkPalette.text[4];
        font-size: Metrics.font-md;
        text: title;
        vertical-alignment: center;
        horizontal-alignment: title-alignment;
    }

    @children
}
