import {DarkPalette} from "../theme.slint";

export component VerticalSeparator inherits Path {
    in property <int> p-elevation: 0;

    width: 1px;
    stroke: DarkPalette.background[root.p-elevation];
    stroke-width: 1px;
    commands: "M 0 0 L 0 1 Z";
}

export component HorizontalSeparator inherits Path {
    in property <int> p-elevation: 0;

    height: 1px;
    stroke: DarkPalette.background[root.p-elevation];
    stroke-width: 1px;
    commands: "M 0 0 L 1 0 Z";
}
