import {DarkPalette} from "../theme.slint";

export component VerticalSeparator {
    width: 1px;
    Path {
        width: 1px;
        stroke: DarkPalette.background[0];
        stroke-width: 1px;
        commands: "M 0 0 L 0 1 Z";
    }
}

export component HorizontalSeparator {
    height: 1px;
    Path {
        height: 1px;
        stroke: DarkPalette.background[0];
        stroke-width: 1px;
        commands: "M 0 0 L 1 0 Z";
    }
}
