import { Metrics, DarkPalette } from "theme.slint";
import { HorizontalBox } from "widgets/layout.slint";

export component EditorBar inherits HorizontalBox {
    height: Metrics.size-xl;
    j-spacing: Metrics.spacing-xl;
    j-rounding: Metrics.radius-md;

    Text {
        color: DarkPalette.text[4];
        font-size: Metrics.font-md;
        vertical-alignment: center;
        text: "Damn look at all the options and shit here it's like Hammer 2!!";
    }
}
