import { Metrics } from "theme.slint";
import { VerticalSeparator } from "widgets/separator.slint";

export component StatusBar inherits Rectangle {
    border-color: black;
    border-width: 1px;
    height: Metrics.size-lg;
    HorizontalLayout {
        alignment: start;
        padding-left: Metrics.padding-lg;
        padding-right: Metrics.padding-lg;
        spacing: Metrics.padding-lg;
        Text {
            font-size: Metrics.font-md;
            vertical-alignment: center;
            text: "Last saved: 18:50";
        }

        VerticalSeparator { }

        Text {
            font-size: Metrics.font-md;
            vertical-alignment: center;
            text: "Saved by: Jayrude";
        }

        VerticalSeparator { }
    }
}
