import { Metrics, DarkPalette } from "theme.slint";
import { HorizontalBox, VerticalSeparator } from "widgets/components.slint";

export component StatusBar inherits HorizontalBox {
    height: Metrics.size-lg;
    p-spacing: Metrics.spacing-lg;
    p-alignment: start;

    Text {
        color: DarkPalette.text[4];
        font-size: Metrics.font-md;
        vertical-alignment: center;
        text: "Last saved: 18:50";
    }

    VerticalSeparator { }

    Text {
        color: DarkPalette.text[4];
        font-size: Metrics.font-md;
        vertical-alignment: center;
        text: "Saved by: Jayrude";
    }

    VerticalSeparator { }
}
