export global Theme {
    in-out property <length> padding-sm: 4px;
    in-out property <length> padding-md: 8px;
    in-out property <length> padding-lg: 16px;
    in-out property <length> padding-xl: 24px;

    in-out property <length> spacing-sm: 4px;
    in-out property <length> spacing-md: 8px;
    in-out property <length> spacing-lg: 16px;
    in-out property <length> spacing-xl: 24px;

    in-out property <length> size-sm: 16px;
    in-out property <length> size-md: 24px;
    in-out property <length> size-lg: 32px;
    in-out property <length> size-xl: 48px;

    in-out property <length> radius-sm: 4px;
    in-out property <length> radius-md: 8px;
    in-out property <length> radius-lg: 16px;
    in-out property <length> radius-xl: 32px;
}
