import { Metrics, DarkPalette } from "theme.slint";
import { Button } from "std-widgets.slint";
import { HorizontalSeparator } from "widgets/separator.slint";
import { VerticalBox } from "widgets/layout.slint";

component ToolBarItem inherits Rectangle {
    width: Metrics.size-lg;
    height: Metrics.size-lg;
    border-radius: Metrics.radius-md;
    background: DarkPalette.background[2];
}

export component ToolBar inherits VerticalBox {
    width: Metrics.size-xl;
    j-rounding: Metrics.radius-md;

    Button {
        checkable: true;
    }

    ToolBarItem { }

    ToolBarItem { }

    ToolBarItem { }

    ToolBarItem { }

    HorizontalSeparator { }

    ToolBarItem { }

    ToolBarItem { }

    ToolBarItem { }

    ToolBarItem { }

    ToolBarItem { }

    ToolBarItem { }

    HorizontalSeparator { }

    ToolBarItem { }

    ToolBarItem { }

    ToolBarItem { }
}
